import { NextResponse } from "next/server";
import * as XLSX from "xlsx";
import { format, subDays, startOfDay, endOfDay } from "date-fns";
import { prisma } from "@/lib/db";
import { requireAdmin } from "@/lib/auth";

type Ctx = { params: Promise<{ id: string }> };

export async function GET(req: Request, ctx: Ctx) {
  const admin = await requireAdmin();
  if (!admin) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const { id } = await ctx.params;

  const { searchParams } = new URL(req.url);
  const formatType = searchParams.get("format") || "csv";
  const timeframe = searchParams.get("timeframe") || "weekly";

  const [cls, settings] = await Promise.all([
    prisma.class.findUnique({
      where: { id },
      include: {
        course: {
          include: {
            department: true,
          },
        },
        people: {
          where: { active: true },
          select: {
            id: true,
            name: true,
            rollNumber: true,
            role: true,
          },
          orderBy: { rollNumber: "asc" },
        },
      },
    }),
    prisma.settings.findUnique({ where: { id: "default" } }).catch(() => null),
  ]);

  if (!cls) {
    return NextResponse.json({ error: "Class not found" }, { status: 404 });
  }

  const collegeName = settings?.collegeName || "KIPS College G-9, Islamabad";
  const studentIds = cls.people.map((p) => p.id);

  let dateFilter: { gte?: Date; lte?: Date } | undefined = undefined;
  let timeframeLabel = "All Recorded Sessions";
  const now = new Date();

  if (timeframe === "weekly") {
    dateFilter = { gte: startOfDay(subDays(now, 6)), lte: endOfDay(now) };
    timeframeLabel = `Last 7 Days (${format(subDays(now, 6), "dd MMM yyyy")} - ${format(now, "dd MMM yyyy")})`;
  } else if (timeframe === "monthly") {
    dateFilter = { gte: startOfDay(subDays(now, 29)), lte: endOfDay(now) };
    timeframeLabel = `Last 30 Days (${format(subDays(now, 29), "dd MMM yyyy")} - ${format(now, "dd MMM yyyy")})`;
  } else if (timeframe === "yearly") {
    dateFilter = { gte: startOfDay(subDays(now, 364)), lte: endOfDay(now) };
    timeframeLabel = `Academic Year (${format(subDays(now, 364), "dd MMM yyyy")} - ${format(now, "dd MMM yyyy")})`;
  }

  const logs = await prisma.attendance.findMany({
    where: {
      personId: { in: studentIds },
      ...(dateFilter ? { markedAt: dateFilter } : {}),
    },
    include: {
      person: true,
    },
    orderBy: { markedAt: "desc" },
  });

  // Calculate distinct session dates
  const sessionDates = new Set<string>();
  logs.forEach((l) => sessionDates.add(format(new Date(l.markedAt), "yyyy-MM-dd")));
  const totalSessions = sessionDates.size;

  // Calculate per-student attended session counts
  const studentAttendedDays = new Map<string, Set<string>>();
  studentIds.forEach((sid) => studentAttendedDays.set(sid, new Set()));
  logs.forEach((l) => {
    studentAttendedDays.get(l.personId)?.add(format(new Date(l.markedAt), "yyyy-MM-dd"));
  });

  // Calculate class average attendance rate
  let totalRateSum = 0;
  const studentStats = cls.people.map((p, idx) => {
    const attended = studentAttendedDays.get(p.id)?.size || 0;
    const rateNumber = totalSessions > 0 ? Math.round((attended / totalSessions) * 100) : 100;
    totalRateSum += rateNumber;

    let standing = "Good";
    if (rateNumber >= 85) standing = "Excellent";
    else if (rateNumber >= 75) standing = "Satisfactory";
    else if (rateNumber >= 50) standing = "Attendance Warning";
    else standing = "Critical Shortage";

    return {
      srNo: idx + 1,
      rollNumber: p.rollNumber,
      name: p.name,
      role: p.role.toUpperCase(),
      attended,
      totalSessions,
      rateStr: `${rateNumber}%`,
      rateNumber,
      standing,
    };
  });

  const avgClassRate = cls.people.length > 0 ? Math.round(totalRateSum / cls.people.length) : 0;
  const generatedAt = format(now, "dd MMM yyyy, hh:mm a");

  // -------------------------------------------------------------
  // EXCEL (XLSX) GENERATION - EXECUTIVE PROFESSIONAL FORMAT
  // -------------------------------------------------------------
  if (formatType === "xlsx") {
    const wb = XLSX.utils.book_new();

    // SHEET 1: ROSTER SUMMARY WITH PROFESSIONAL BANNER
    const summaryAoa: (string | number)[][] = [
      [collegeName.toUpperCase()],
      ["OFFICIAL CLASS ATTENDANCE & ROSTER REPORT"],
      [""],
      ["Department:", cls.course.department.name, "", "Report Period:", timeframeLabel],
      ["Course:", cls.course.name, "", "Total Enrolled:", cls.people.length],
      ["Class:", cls.name, "", "Conducted Sessions:", totalSessions],
      ["Class Average:", `${avgClassRate}%`, "", "Generated At:", generatedAt],
      ["Generated By:", admin.name || "Administrator", "", "Report Status:", "Verified Official Record"],
      [""],
      // Table Header Row
      [
        "Sr. No.",
        "Roll Number",
        "Student Name",
        "Role",
        "Sessions Attended",
        "Total Sessions",
        "Attendance Rate",
        "Academic Standing",
      ],
    ];

    // Data rows
    studentStats.forEach((s) => {
      summaryAoa.push([
        s.srNo,
        s.rollNumber,
        s.name,
        s.role,
        s.attended,
        s.totalSessions,
        s.rateStr,
        s.standing,
      ]);
    });

    const wsSummary = XLSX.utils.aoa_to_sheet(summaryAoa);

    // Set column widths for Sheet 1
    wsSummary["!cols"] = [
      { wch: 9 },  // Sr No
      { wch: 16 }, // Roll Number
      { wch: 28 }, // Student Name
      { wch: 12 }, // Role
      { wch: 18 }, // Sessions Attended
      { wch: 16 }, // Total Sessions
      { wch: 17 }, // Attendance Rate
      { wch: 22 }, // Academic Standing
    ];

    XLSX.utils.book_append_sheet(wb, wsSummary, "Attendance Summary");

    // SHEET 2: DETAILED CHRONOLOGICAL SCAN LOGS
    const logsAoa: (string | number)[][] = [
      [collegeName.toUpperCase()],
      [`CHRONOLOGICAL ATTENDANCE LOGS - CLASS: ${cls.name.toUpperCase()}`],
      [""],
      ["Class:", cls.name, "Course:", cls.course.name, "Department:", cls.course.department.name],
      ["Timeframe:", timeframeLabel, "Total Scans:", logs.length, "Generated:", generatedAt],
      [""],
      [
        "Sr. No.",
        "Date",
        "Time",
        "Roll Number",
        "Student Name",
        "Attendance Status",
        "Verification Method",
        "Confidence %",
        "Remarks / Notes",
      ],
    ];

    if (logs.length === 0) {
      logsAoa.push(["-", "No scan logs recorded for this timeframe", "", "", "", "", "", "", ""]);
    } else {
      logs.forEach((l, idx) => {
        const markedDate = new Date(l.markedAt);
        logsAoa.push([
          idx + 1,
          format(markedDate, "yyyy-MM-dd"),
          format(markedDate, "hh:mm:ss a"),
          l.person.rollNumber,
          l.person.name,
          (l.status || "present").toUpperCase(),
          l.method === "face" ? "Face Recognition Kiosk" : "Manual Verification",
          l.confidence != null ? `${Math.round(l.confidence * 100)}%` : "N/A",
          l.note || "-",
        ]);
      });
    }

    const wsLogs = XLSX.utils.aoa_to_sheet(logsAoa);

    // Set column widths for Sheet 2
    wsLogs["!cols"] = [
      { wch: 9 },  // Sr No
      { wch: 14 }, // Date
      { wch: 15 }, // Time
      { wch: 16 }, // Roll Number
      { wch: 28 }, // Student Name
      { wch: 18 }, // Attendance Status
      { wch: 24 }, // Verification Method
      { wch: 15 }, // Confidence %
      { wch: 25 }, // Remarks
    ];

    XLSX.utils.book_append_sheet(wb, wsLogs, "Verification Logs");

    const cleanClassName = cls.name.replace(/[^a-zA-Z0-9_-]/g, "_");
    const buf = XLSX.write(wb, { type: "buffer", bookType: "xlsx" });

    return new NextResponse(buf, {
      headers: {
        "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "Content-Disposition": `attachment; filename="${cleanClassName}_Attendance_Report_${timeframe}.xlsx"`,
      },
    });
  }

  // -------------------------------------------------------------
  // CSV GENERATION - PROFESSIONAL STRUCTURED FORMAT
  // -------------------------------------------------------------
  const cleanClassName = cls.name.replace(/[^a-zA-Z0-9_-]/g, "_");

  const csvLines: string[] = [
    `"${collegeName.toUpperCase()}"`,
    `"OFFICIAL ATTENDANCE REPORT - CLASS ${cls.name.toUpperCase()}"`,
    `"Department: ${cls.course.department.name}","Course: ${cls.course.name}","Class: ${cls.name}"`,
    `"Period: ${timeframeLabel}","Total Enrolled: ${cls.people.length}","Total Conducted Sessions: ${totalSessions}","Class Average: ${avgClassRate}%"`,
    `"Generated At: ${generatedAt}","Generated By: ${admin.name || "Administrator"}"`,
    "",
    `"STUDENT ATTENDANCE SUMMARY"`,
    `"Sr. No.","Roll Number","Student Name","Role","Sessions Attended","Total Sessions","Attendance Rate","Standing"`,
  ];

  studentStats.forEach((s) => {
    csvLines.push(
      `"${s.srNo}","${s.rollNumber}","${s.name.replace(/"/g, '""')}","${s.role}","${s.attended}","${s.totalSessions}","${s.rateStr}","${s.standing}"`
    );
  });

  if (logs.length > 0) {
    csvLines.push("");
    csvLines.push(`"DETAILED VERIFICATION LOGS"`);
    csvLines.push(`"Sr. No.","Date","Time","Roll Number","Student Name","Status","Method","Confidence","Notes"`);

    logs.forEach((l, idx) => {
      const markedDate = new Date(l.markedAt);
      const conf = l.confidence != null ? `${Math.round(l.confidence * 100)}%` : "N/A";
      const method = l.method === "face" ? "Face Recognition Kiosk" : "Manual";
      csvLines.push(
        `"${idx + 1}","${format(markedDate, "yyyy-MM-dd")}","${format(markedDate, "hh:mm:ss a")}","${l.person.rollNumber}","${l.person.name.replace(/"/g, '""')}","${(l.status || "present").toUpperCase()}","${method}","${conf}","${(l.note || "").replace(/"/g, '""')}"`
      );
    });
  }

  return new NextResponse(csvLines.join("\r\n"), {
    headers: {
      "Content-Type": "text/csv; charset=utf-8",
      "Content-Disposition": `attachment; filename="${cleanClassName}_Attendance_Report_${timeframe}.csv"`,
    },
  });
}
